# Generated by Django 5.2.5 on 2025-09-09 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=50, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=5, verbose_name='Preço')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade do produto em estoque', max_digits=5, verbose_name='Quantidade')),
                ('fornecedor', models.ForeignKey(help_text='Nome do fornecedor', on_delete=django.db.models.deletion.PROTECT, related_name='fornecedor', to='fornecedores.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
