# Generated by Django 5.2.5 on 2025-09-23 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('servicos', '0003_servico_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('A', 'Agendado'), ('R', 'Realizado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, max_length=300, null=True, verbose_name='Observações')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço do serviço', max_digits=6, verbose_name='Preço')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='agendamentos.agendamento', verbose_name='Agendamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='servicos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço realizado',
                'verbose_name_plural': 'Serviços realizados',
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ManyToManyField(through='agendamentos.OrdemServicos', to='servicos.servico', verbose_name='Serviço'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicos',
            constraint=models.UniqueConstraint(fields=('agendamento', 'servico'), name='constraint_agendamento'),
        ),
    ]
