# Generated by Django 5.2.5 on 2025-09-25 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_ordemservicos_agendamento_servico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-horario'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(default='A', help_text='Status do agendamento', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='ordemservicos',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='agendamentos.agendamento', verbose_name='Agendamento'),
        ),
    ]
