# Generated by Django 5.2.5 on 2025-10-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendamento_options_agendamento_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-horario'], 'permissions': (('fechar_agendamento', 'Permite fazer o fechar  de um agendamento'),), 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
    ]
