# Generated by Django 5.2.5 on 2025-09-25 18:26

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servico_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': [django.db.models.functions.text.Upper('nome')], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='produtosservico',
            name='servico',
            field=models.ForeignKey(help_text='Nome do serviço realizado', on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
